---
# For use with packer and ansible-local provisioner.
- hosts: all
  connection: local
  sudo: yes
  roles:
    - python3
  vars:
    python3_pip_packages:
      - "git+ssh://git@github.com/ridecharge/curbformation.git#egg=curbformation"